name: Build and deploy Node.js app

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup Node.js environment
      - name: Set up Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build -- --prod

      # Deploy to Azure Web apps staging slot
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-lbarq-node-01 # Replace with your app name

      # Azure logout
      - name: logout
        run: |
          az logout
